@ECHO OFF
echo Converting Line Endings...
rem powershell -Command (Get-Content "main.c") | Set-Content "main.c"
powershell  "& "".\linux2windows.ps1"""
echo Fixing Path to Files...
cscript replace.vbs "main.c" "./db/" ".\\db\\"
echo Changing "clear" to "cls"...
cscript replace.vbs "main.c" "clear" "cls"
echo Done