@ECHO OFF
echo Converting Line Endings...
powershell -Command (Get-Content "main.c") | Set-Content "main.c"
echo Fixing Path to Files...
cscript replace.vbs "main.c" "./db/" ".\\db\\"
echo Changing "clear" to "cls"...
cscript replace.vbs "main.c" "clear" "cls"
echo Done